http:
  enabled: false

input:
  kafka:
    addresses: [ localhost:9092 ]
    consumer_group: benthos-redpanda
    topics: [ encrypted ]

pipeline:
  processors:
    #- schema_registry_decode:
    #    url: http://redpanda:8081

    - decrypt:
        fields: [ Name, Address ]
        keyString: 532468f222e3394d3363ca4bbc19235a2590ae38a456e573038ea0b508b2d467

    - catch:
      - log:
          level: ERROR
          message: ${! error() }
      - bloblang: root = deleted()

output:
  kafka:
    addresses: [ localhost:9092 ]
    topic: decrypted

